"use strict";

import { TableDefinition } from "./types-ggs_backups";

export function backups(): TableDefinition {
  var definition: TableDefinition = {
    name: "backups",
    elementName: "backup",
    title: "Backups",
    tableName: "backups",
    editable:true,
    allow: {import:true},
    fields: [
        //campo propios:
        { name: "verificado_procesamiento", title:'verif proc', typeName: "boolean"},
        { name: "observaciones", title:'obs backup', typeName: "text"},
        { name: "resul_proc", typeName: "integer"},
		{ name: "web_proc"	, title:'web_proc', typeName: "text"},
        
        { name: "lote", typeName: "integer", editable: false},
        
        // //campos para codificacion - anulados para esta prueba de concepto
        // { name: "cno_padre",        typeName: "integer"},
        // { name: "ciuo_padre",       typeName: "integer"},
        // { name: "cno_madre",        typeName: "integer"},
        // { name: "ciuo_madre",       typeName: "integer"},
        // { name: "cno_ocup_actual",  typeName: "integer"},
        // { name: "ciuo_ocup_actual", typeName: "integer"},
        // { name: "cno_ocup_anterior",  typeName: "integer"},
        // { name: "ciuo_ocup_anterior", typeName: "integer"},
        // { name: "cno_ocup_pareja",  typeName: "integer"},
        // { name: "ciuo_ocup_pareja", typeName: "integer"},

        //campos fuentes externas:
        // campos agregados de backups CAWI e INT enviados por alex 7/11
        { name: "respid", typeName: 'text', editable:false},
		//decision Silvana 10/11
		// columnas solo INT
		{ name:"interviewer_id"          , typeName: "text", editable: false },
		{ name:"interviewer_name"        , typeName: "text", editable: false },
		{ name:"intst"                   , typeName: "text", editable: false },
		{ name:"b17rep01"                , typeName: "text", editable: false },
		{ name:"b17rep02"                , typeName: "text", editable: false },
		{ name:"b17rep04"                , typeName: "text", editable: false },
		{ name:"b17rep06"                , typeName: "text", editable: false },
		{ name:"begindate"               , typeName: "text", editable: false },
		{ name:"begintime"               , typeName: "text", editable: false },
		{ name:"enddate"                 , typeName: "text", editable: false },
		{ name:"endtime"                 , typeName: "text", editable: false },
		
		// columnas del bkp CAWI  
		{ name: "intdate"                , typeName: "text", editable: false  },
		{ name: "instrument"             , typeName: "text", editable: false  },
		{ name: "mode"                   , typeName: "text", editable: false  },
		{ name: "status"                 , typeName: "text", editable: false  },
		{ name: "agreedintro"            , typeName: "text", editable: false  },
		{ name: "complete"               , typeName: "text", editable: false  },
		{ name: "last_var"               , typeName: "text", editable: false  },
		{ name: "pct_dk_rf"              , typeName: "text", editable: false  },
		{ name: "gender"                 , typeName: "text", editable: false  },
		{ name: "age"                    , typeName: "text", editable: false  },
		{ name: "rooms"                  , typeName: "text", editable: false  },
		{ name: "housingstatus"          , typeName: "text", editable: false  },
		{ name: "hh_mosttime"            , typeName: "text", editable: false  },
		{ name: "householdmembers"       , typeName: "text", editable: false  },
		{ name: "numbiol"                , typeName: "text", editable: false  },
		{ name: "numstep"                , typeName: "text", editable: false  },
		{ name: "numadopt"               , typeName: "text", editable: false  },
		{ name: "nkidstotal"             , typeName: "text", editable: false  },
		{ name: "prevpartner_samehh"     , typeName: "text", editable: false  },
		{ name: "livingwith_newpartner"  , typeName: "text", editable: false  },
		{ name: "partnerage"             , typeName: "text", editable: false  },
		{ name: "hascorespartner"        , typeName: "text", editable: false  },
		{ name: "hascoreschildunder15"   , typeName: "text", editable: false  },
		{ name: "mumcores"               , typeName: "text", editable: false  },
		{ name: "dadcores"               , typeName: "text", editable: false  },
		{ name: "adopt_step_fos"         , typeName: "text", editable: false  },
		{ name: "mother_alive"           , typeName: "text", editable: false  },
		{ name: "father_alive"           , typeName: "text", editable: false  },
		{ name: "life_satisfaction"      , typeName: "text", editable: false  },
		{ name: "general_health"         , typeName: "text", editable: false  },
		{ name: "b1dem01"                , typeName: "text", editable: false  },
		{ name: "b1dem02"                , typeName: "text", editable: false  },
		{ name: "b1dem02_y"              , typeName: "text", editable: false  },
		{ name: "b1dem202_m"             , typeName: "text", editable: false  },
		{ name: "b10hhd01b"              , typeName: "text", editable: false  },
		{ name: "b10hhd04_1"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_2"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_3"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_4"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_5"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_6"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_7"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_8"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_9"             , typeName: "text", editable: false  },
		{ name: "b10hhd04_10"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_11"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_12"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_13"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_14"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_15"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_16"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_17"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_18"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_19"            , typeName: "text", editable: false  },
		{ name: "b10hhd04_20"            , typeName: "text", editable: false  },
		{ name: "b10mem03_1"             , typeName: "text", editable: false  },
		{ name: "b10mem03_2"             , typeName: "text", editable: false  },
		{ name: "b10mem03_3"             , typeName: "text", editable: false  },
		{ name: "b10mem03_4"             , typeName: "text", editable: false  },
		{ name: "b10mem03_5"             , typeName: "text", editable: false  },
		{ name: "b10mem03_6"             , typeName: "text", editable: false  },
		{ name: "b10mem03_7"             , typeName: "text", editable: false  },
		{ name: "b10mem03_8"             , typeName: "text", editable: false  },
		{ name: "b10mem03_9"             , typeName: "text", editable: false  },
		{ name: "b10mem03_10"            , typeName: "text", editable: false  },
		{ name: "b10mem03_11"            , typeName: "text", editable: false  },
		{ name: "b10mem03_12"            , typeName: "text", editable: false  },
		{ name: "b10mem03_13"            , typeName: "text", editable: false  },
		{ name: "b10mem03_14"            , typeName: "text", editable: false  },
		{ name: "b10mem03_15"            , typeName: "text", editable: false  },
		{ name: "b10mem03_16"            , typeName: "text", editable: false  },
		{ name: "b10mem03_17"            , typeName: "text", editable: false  },
		{ name: "b10mem03_18"            , typeName: "text", editable: false  },
		{ name: "b10mem03_19"            , typeName: "text", editable: false  },
		{ name: "b10mem03_20"            , typeName: "text", editable: false  },
		{ name: "b10mem03_y_1"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_2"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_3"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_4"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_5"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_6"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_7"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_8"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_9"           , typeName: "text", editable: false  },
		{ name: "b10mem03_y_10"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_11"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_12"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_13"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_14"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_15"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_16"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_17"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_18"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_19"          , typeName: "text", editable: false  },
		{ name: "b10mem03_y_20"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_1"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_2"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_3"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_4"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_5"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_6"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_7"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_8"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_9"           , typeName: "text", editable: false  },
		{ name: "b10mem03_m_10"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_11"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_12"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_13"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_14"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_15"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_16"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_17"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_18"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_19"          , typeName: "text", editable: false  },
		{ name: "b10mem03_m_20"          , typeName: "text", editable: false  },
		{ name: "b11par00"               , typeName: "text", editable: false  },
		{ name: "b11gen01"               , typeName: "text", editable: false  },
		{ name: "b11gen02"               , typeName: "text", editable: false  },
		{ name: "b11gen03"               , typeName: "text", editable: false  },
		{ name: "b11gen15a"              , typeName: "text", editable: false  },
		{ name: "b11gen15au"             , typeName: "text", editable: false  },
		{ name: "b11gen21"               , typeName: "text", editable: false  },
		{ name: "b11gen35"               , typeName: "text", editable: false  },
		{ name: "b11gen07"               , typeName: "text", editable: false  },
		{ name: "b11gen15b"              , typeName: "text", editable: false  },
		{ name: "b11gen15bu"             , typeName: "text", editable: false  },
		{ name: "b11gen29a"              , typeName: "text", editable: false  },
		{ name: "b11gen29au"             , typeName: "text", editable: false  },
		{ name: "b11gen29b"              , typeName: "text", editable: false  },
		{ name: "b11gen29bu"             , typeName: "text", editable: false  },
		{ name: "b11gen54"               , typeName: "text", editable: false  },
		{ name: "b11gen55"               , typeName: "text", editable: false  },
		{ name: "b11gen56"               , typeName: "text", editable: false  },
		{ name: "b11par10"               , typeName: "text", editable: false  },
		{ name: "b11par11a1"             , typeName: "text", editable: false  },
		{ name: "b11par11a2"             , typeName: "text", editable: false  },
		{ name: "b11par11a3"             , typeName: "text", editable: false  },
		{ name: "b11par11a4"             , typeName: "text", editable: false  },
		{ name: "b11par11a5"             , typeName: "text", editable: false  },
		{ name: "b11par11a6"             , typeName: "text", editable: false  },
		{ name: "b11par11a7"             , typeName: "text", editable: false  },
		{ name: "b11par11a8"             , typeName: "text", editable: false  },
		{ name: "b11par11a9"             , typeName: "text", editable: false  },
		{ name: "b11par11a10"            , typeName: "text", editable: false  },
		{ name: "b11par11b"              , typeName: "text", editable: false  },
		{ name: "b11par12a1"             , typeName: "text", editable: false  },
		{ name: "b11par12a2"             , typeName: "text", editable: false  },
		{ name: "b11par12a3"             , typeName: "text", editable: false  },
		{ name: "b11par12a4"             , typeName: "text", editable: false  },
		{ name: "b11par12a5"             , typeName: "text", editable: false  },
		{ name: "b11par12a6"             , typeName: "text", editable: false  },
		{ name: "b11par12a7"             , typeName: "text", editable: false  },
		{ name: "b11par12a8"             , typeName: "text", editable: false  },
		{ name: "b11par12a9"             , typeName: "text", editable: false  },
		{ name: "b11par12a10"            , typeName: "text", editable: false  },
		{ name: "b11par12a11"            , typeName: "text", editable: false  },
		{ name: "b11par12b"              , typeName: "text", editable: false  },
		{ name: "b11par13a1"             , typeName: "text", editable: false  },
		{ name: "b11par13a2"             , typeName: "text", editable: false  },
		{ name: "b11par13a3"             , typeName: "text", editable: false  },
		{ name: "b11par13a4"             , typeName: "text", editable: false  },
		{ name: "b11par13a5"             , typeName: "text", editable: false  },
		{ name: "b11par13a6"             , typeName: "text", editable: false  },
		{ name: "b11par13a7"             , typeName: "text", editable: false  },
		{ name: "b11par13a8"             , typeName: "text", editable: false  },
		{ name: "b11par13a9"             , typeName: "text", editable: false  },
		{ name: "b11par13b"              , typeName: "text", editable: false  },
		{ name: "b11par14a1"             , typeName: "text", editable: false  },
		{ name: "b11par14a2"             , typeName: "text", editable: false  },
		{ name: "b11par14a3"             , typeName: "text", editable: false  },
		{ name: "b11par14a4"             , typeName: "text", editable: false  },
		{ name: "b11par14a5"             , typeName: "text", editable: false  },
		{ name: "b11par14a6"             , typeName: "text", editable: false  },
		{ name: "b11par14a7"             , typeName: "text", editable: false  },
		{ name: "b11par14a8"             , typeName: "text", editable: false  },
		{ name: "b11par14a9"             , typeName: "text", editable: false  },
		{ name: "b11par14a10"            , typeName: "text", editable: false  },
		{ name: "b11par14a11"            , typeName: "text", editable: false  },
		{ name: "b11par14a12"            , typeName: "text", editable: false  },
		{ name: "b11par14a13"            , typeName: "text", editable: false  },
		{ name: "b11par14a14"            , typeName: "text", editable: false  },
		{ name: "b11par14b"              , typeName: "text", editable: false  },
		{ name: "b12int01a"              , typeName: "text", editable: false  },
		{ name: "b12int01b"              , typeName: "text", editable: false  },
		{ name: "b12int01c"              , typeName: "text", editable: false  },
		{ name: "b12int01d"              , typeName: "text", editable: false  },
		{ name: "b12int01e"              , typeName: "text", editable: false  },
		{ name: "b12int01f"              , typeName: "text", editable: false  },
		{ name: "b12int01g"              , typeName: "text", editable: false  },
		{ name: "b12int01h"              , typeName: "text", editable: false  },
		{ name: "b12int01i"              , typeName: "text", editable: false  },
		{ name: "b13ecr01"               , typeName: "text", editable: false  },
		{ name: "b13dem07"               , typeName: "text", editable: false  },
		{ name: "b13dem08"               , typeName: "text", editable: false  },
		{ name: "b13dem08_y"             , typeName: "text", editable: false  },
		{ name: "b13dem08_m"             , typeName: "text", editable: false  },
		{ name: "b13dem06"               , typeName: "text", editable: false  },
		{ name: "b13wrk03"               , typeName: "text", editable: false  },
		{ name: "b13wrk03_y"             , typeName: "text", editable: false  },
		{ name: "b13wrk03_m"             , typeName: "text", editable: false  },
		{ name: "b13ecr05b"              , typeName: "text", editable: false  },
		{ name: "b13ecr05b_y"            , typeName: "text", editable: false  },
		{ name: "b13ecr05b_m"            , typeName: "text", editable: false  },
		{ name: "b13ecr061"              , typeName: "text", editable: false  },
		{ name: "b13ecr062"              , typeName: "text", editable: false  },
		{ name: "b13ecr063"              , typeName: "text", editable: false  },
		{ name: "b13ecr064"              , typeName: "text", editable: false  },
		{ name: "b13ecr065"              , typeName: "text", editable: false  },
		{ name: "b13ecr066"              , typeName: "text", editable: false  },
		{ name: "b13ecr067"              , typeName: "text", editable: false  },
		{ name: "b13ecr068"              , typeName: "text", editable: false  },
		{ name: "b13ecr069"              , typeName: "text", editable: false  },
		{ name: "b13ecr0610"             , typeName: "text", editable: false  },
		{ name: "b13ecr0611"             , typeName: "text", editable: false  },
		{ name: "b13ecr0612"             , typeName: "text", editable: false  },
		{ name: "b13wrk02"               , typeName: "text", editable: false  },
		{ name: "b13wrk04_3601"          , typeName: "text", editable: false  },
		{ name: "b13wrk04_3602"          , typeName: "text", editable: false  },
		{ name: "b13wrk06"               , typeName: "text", editable: false  },
		{ name: "b13wrk07"               , typeName: "text", editable: false  },
		{ name: "b13ecr10"               , typeName: "text", editable: false  },
		{ name: "b13ecr11"               , typeName: "text", editable: false  },
		{ name: "b13wrk11"               , typeName: "text", editable: false  },
		{ name: "b13wrk13"               , typeName: "text", editable: false  },
		{ name: "b13wrk16a"              , typeName: "text", editable: false  },
		{ name: "b13wrk18"               , typeName: "text", editable: false  },
		{ name: "b13wrk20"               , typeName: "text", editable: false  },
		{ name: "b13att11b"              , typeName: "text", editable: false  },
		{ name: "b13att11d"              , typeName: "text", editable: false  },
		{ name: "b13wrk26_3603"          , typeName: "text", editable: false  },
		{ name: "b13wrk27_3604"          , typeName: "text", editable: false  },
		{ name: "b13wrk27_3605"          , typeName: "text", editable: false  },
		{ name: "b14dem25"               , typeName: "text", editable: false  },
		{ name: "b14dem26"               , typeName: "text", editable: false  },
		{ name: "b12ecp031"              , typeName: "text", editable: false  },
		{ name: "b12ecp032"              , typeName: "text", editable: false  },
		{ name: "b12ecp033"              , typeName: "text", editable: false  },
		{ name: "b12ecp034"              , typeName: "text", editable: false  },
		{ name: "b12ecp035"              , typeName: "text", editable: false  },
		{ name: "b12ecp036"              , typeName: "text", editable: false  },
		{ name: "b12ecp037"              , typeName: "text", editable: false  },
		{ name: "b12ecp038"              , typeName: "text", editable: false  },
		{ name: "b12ecp039"              , typeName: "text", editable: false  },
		{ name: "b12ecp0310"             , typeName: "text", editable: false  },
		{ name: "b12ecp0311"             , typeName: "text", editable: false  },
		{ name: "b12ecp0312"             , typeName: "text", editable: false  },
		{ name: "b14wrk32"               , typeName: "text", editable: false  },
		{ name: "b14wrk35"               , typeName: "text", editable: false  },
		{ name: "b14ecp06"               , typeName: "text", editable: false  },
		{ name: "b14ecp07"               , typeName: "text", editable: false  },
		{ name: "b14wrk38"               , typeName: "text", editable: false  },
		{ name: "b14wrk40"               , typeName: "text", editable: false  },
		{ name: "b14wrk42"               , typeName: "text", editable: false  },
		{ name: "b14wrk44"               , typeName: "text", editable: false  },
		{ name: "b14wrk46"               , typeName: "text", editable: false  },
    ],
    primaryKey: ["lote", "respid"],
    constraints:[
        {constraintType:'unique', fields:['respid', 'verificado_procesamiento']},
        {constraintType:'check', expr:'verificado_procesamiento in (null,true)', consName:'verificado_procesamiento puede true o nulo'},
    ],
    foreignKeys: [{ references: "lotes", fields: ["lote"] }],
    // hiddenColumns: [
    //    "modificado",
    // ],
  };
  return definition;
}
